BOARD_TAG    = mega2560
MONITOR_PORT = /dev/ttyACM0
ARDUINO_DIR  = /usr/share/arduino
USER_LIB_PATH+=lib
ARDUINO_LIBS+=ros_lib
ARDUINO_LIBS+=SoftwareSerial
ARDUINO_LIBS+=Sabertooth
include /usr/share/arduino/Arduino.mk